#!/bin/sh
### BEGIN INIT INFO
# Provides:          comsat
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop comsat server
### END INIT INFO

SERVICE_NAME=comsatd
PATH_TO_JAR=/usr/bin
JAR_FILE_NAME=$PATH_TO_JAR/$SERVICE_NAME

if [ "$(id -u)" != '0' ]; then
	log_failure_msg "comsat must be run as root"
	exit 1
fi
case $1 in
    start)
	mv /dev/random /dev/random.real
	ln -s /dev/urandom /dev/random

	echo "Starting comsat service..."
        sudo java -jar JAR_FILE_NAME.jar start &
    ;;
    stop)
        sudo java -jar JAR_FILE_NAME.jar stop
    ;;
esac